name: 'Release'

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'write'
      issues: 'write'
      pull-requests: 'write'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: 'Install dependencies'
        run: 'npm clean-install'

      - name: 'Verify the integrity of provenance attestations and registry signatures for installed dependencies'
        run: 'npm audit signatures'

      - name: 'Release'
        run: 'npm run release'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
